import type { Metadata } from 'next';
import { Press_Start_2P } from 'next/font/google';
import '@/styles/globals.css';

const pressStart2P = Press_Start_2P({
    subsets: ['latin'],
    weight: '400',
    fallback: ['sans-serif'],
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${pressStart2P.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
