import type { Metadata } from 'next';
import { Bitter } from 'next/font/google';
import '@/styles/globals.css';

const bitter = Bitter({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${bitter.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
